FROM golang:1.25-alpine AS build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o api .

FROM alpine:3.21

WORKDIR /app
COPY --from=build /app/api /app/api

EXPOSE 8080
CMD ["/app/api"]
